### PR TITLE
node16: Builds on node v16.13.1

### PR DESCRIPTION
**Pull request by key-networks**

### CODE REVIEW

**Comment by key-networks** [comment]
This builds with node v16.13.1, but execution fails at:
```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/key-networks/ztncui/node_modules/argon2/build/Release/argon2.node)
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/snapshot/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/src/node_modules/argon2/argon2.js:3:37)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by kmahyyg** [comment]
> This builds with node v16.13.1, but execution fails at:
> 
> ```
> pkg/prelude/bootstrap.js:1740
>       throw error;
>       ^
> 
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/key-networks/ztncui/node_modules/argon2/build/Release/argon2.node)
>     at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
>     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at Module.require (pkg/prelude/bootstrap.js:1719:31)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at bindings (/snapshot/src/node_modules/bindings/bindings.js:112:48)
>     at Object.<anonymous> (/snapshot/src/node_modules/argon2/argon2.js:3:37)
>     at Module._compile (pkg/prelude/bootstrap.js:1794:22) {
>   code: 'ERR_DLOPEN_FAILED'
> }
> ```

This problem is related to a relatively old system (like CentOS6/7) running a binary built on a new OS (like Ubuntu 20.04). Please upgrade your system or build the code from old systems instead.

Also, Please check my PR due to a serious SECURITY issue for generating password.

**Comment by kmahyyg** [comment]
make sure you do mention to keep the docker environment up to date with you when you merge this PR. Thanks a lot.

**Comment by key-networks** [comment]
Thanks @kmahyyg for the pointers.  I am building on Fedora 35 and was trying to run on Ubuntu 20.04 (IIRC).  I'll have a look over the next few days when I get a chance.

**Comment by key-networks** [comment]
@kmahyyg - as you pointed out, it was a clash between the build environment and the deployment environment.  It seems to deploy fine on a Fedora 35 VM.

**Comment by kmahyyg** [comment]
> 

Yes, so either you built on relatively old machine, then run on new machine. Or use the same environment on both machine.

**Comment by key-networks** [comment]
@kmahyyg I wonder if you could give me some pointers on how to do this?  My build system has been upgraded to Fedora 35 and their are other dependencies in the build process to produce the .rpm and .deb artifacts, so I was thinking it would be neat if the argon2 module alone (built with node-gyp) could be built in a docker container with nodejs 16 where it is statically linked against and older version of libstdc++.a (see https://github.com/key-networks/ztncui/blob/master/build/binding.gyp.patch) so that it can work on older systems.  Alternately, I guess all the nodejs modules could be built in a docker container and then the artifact presented to the host machine for packaging and rpm signing.

It's a while since I've worked on this stuff, so it will take me a while to get my brain in gear to do it, so I was wondering if you could give me some pointers to try help speed things up so that I can merge this PR sooner?  Many thanks!

**Comment by kmahyyg** [comment]
This is related to how Linux loads the binary files and executes it. Simplified saying, they are all linked against a must-have library called `glibc` (If not statically build), `glibc` is not compatible. It is the base of the whole program.

The old version `glibc` doesn't guarantee to have the same dependencies when you build the program with newer `glibc`.

So you have two choices here:

- statically build and link the program. However, Nodejs is the one I'm not familiar with. It should be difficult to build the program in this way.
- Build on a relatively old machine, run everywhere. That's what I recommended. But it depends on your choice to be compatible with which distribution and versions. For example, to run on newer RH-based OS, you could try to build on CentOS 7 or RHEL 7 or even something older. As for Debian, Debian 8(EOL)/9 should be fine. To be compatible with older legacy OS, you might need to involve more time. So you should have really have a cautious consideration about that. 

Packaging and Signing should be done on the same environment, not in Host OS, but in Docker only.

**Comment by key-networks** [comment]
@kmahyyg - just a heads-up that I'm about to merge this branch into master.

**Comment by kmahyyg** [comment]
got it.

**Comment by key-networks** [comment]
@kmahyyg I'm not merging just yet - there may be a bug.  I tested on a VM on my local machine.  After attempting to authorize a new node and giving it a name, when I pressed Refresh, it went straight back to the login page.  I have put the DEB package here: https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.8.4_amd64.deb
and the RPM can be installed with:
`sudo dnf --enablerepo=ztncui-testing upgrade ztncui`

Please can someone help with testing to verify if this is a bug, or some network issue with my VM.

**Comment by key-networks** [comment]
@kmahyyg the ztncui-aio image builds, so I am merging this now.

If someone has a problem with the deb or rpm package, please open a new ticket.

**Pull request merged**
